package com.coopcredit.application.infrastructure.adapter.in.web.mapper;

import com.coopcredit.application.domain.model.Afiliado;
import com.coopcredit.application.infrastructure.adapter.in.web.dto.AfiliadoRegisterRequest;
import com.coopcredit.application.infrastructure.adapter.in.web.dto.AfiliadoResponse;
import com.coopcredit.application.infrastructure.adapter.in.web.dto.AfiliadoUpdateRequest;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingConstants;

/**
 * MapStruct mapper for converting between DTOs and domain model.
 * This mapper is automatically implemented by MapStruct at compile time.
 */
@Mapper(componentModel = MappingConstants.ComponentModel.SPRING)
public interface AfiliadoDtoMapper {

    /**
     * Converts registration request DTO to domain model.
     * ID is not mapped from request (will be generated by database).
     * 
     * @param request the registration request DTO
     * @return the domain model
     */
    @Mapping(target = "id", ignore = true)
    Afiliado toDomain(AfiliadoRegisterRequest request);

    /**
     * Converts update request DTO to domain model.
     * ID, documento, and fechaAfiliacion are not mapped from update request.
     * 
     * @param request the update request DTO
     * @return the domain model
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "documento", ignore = true)
    @Mapping(target = "fechaAfiliacion", ignore = true)
    Afiliado toDomain(AfiliadoUpdateRequest request);

    /**
     * Converts domain model to response DTO.
     * 
     * @param afiliado the domain model
     * @return the response DTO
     */
    AfiliadoResponse toResponse(Afiliado afiliado);
}
